"""baseline: full current schema

Builds every table from the live SQLAlchemy metadata rather than hand-written
DDL, so it is identical to the app's create_all and works on both Postgres
(prod) and SQLite (tests). Future schema changes get their own autogenerated
revisions on top of this.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-28
"""
from typing import Sequence, Union

from app.database import Base
import app.models  # noqa: F401 — populates Base.metadata
from alembic import op

revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
